name: Chrome Remote Desktop

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  
jobs:
  build:
    runs-on: Windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/miladphoenix/i/main/WinrarSirMeti.exe -OutFile WinrarSirMeti.exe
        Invoke-WebRequest https://cdn.akamai.steamstatic.com/client/installer/SteamSetup.exe -OutFile Steam.exe
        Invoke-WebRequest https://cdn.glitch.global/34ddfdc4-5ab2-4acc-9f00-f7a00a9d0bff/PortableApps.com_Platform_Setup_22.0.1.paf.exe?v=1664903830573 -OutFile Portableapps.exe
    - name: Copy To Desktop
      run: |
        copy WinrarSirMeti.exe C:\Users\Public\Desktop\WinrarSirMeti.exe
        copy Portableapps.exe C:\Users\Public\Desktop\Portableapps.exe
        copy Steam.exe C:\Users\Public\Desktop\Steam.exe

    - name: Install Apps
      run: cmd /c C:\Users\Public\Desktop\WinrarSirMeti.exe WinrarSirMeti.exe /s
    - name: Keep Alive FOr 60 Minutes
      run: ./timeout.ps1
